language: ruby
script: rake
notifications:
  recipients:
    - brixen@gmail.com
    - d.bussink@gmail.com
  email:
    on_success: change
    on_failure: always
rvm:
  - 1.9.3
matrix:
  exclude:
    - rvm: 1.9.3
  include:
    - rvm: rbx-2.1.1
      env: RBX_RUBY_COMPAT=2.1.0
    - rvm: rbx-head
      env: RBX_RUBY_COMPAT=2.1.0
