language: ruby
script: rake
notifications:
  recipients:
    - brixen@gmail.com
    - d.bussink@gmail.com
  email:
    on_success: change
    on_failure: always
rvm:
  - 1.9.3
matrix:
  exclude:
    - rvm: 1.9.3
  include:
    - rvm: rbx-10.0.0
      env: RBX_RUBY_COMPAT=10.0.0 RBX_VERSION=10.0.0
    - rvm: rbx-2.2.4
      env: RBX_RUBY_COMPAT=2.1.0 RBX_VERSION=2.2.4
    - rvm: rbx-2.2
      env: RBX_RUBY_COMPAT=2.1.0 RBX_VERSION=2.2.4
    - rvm: rbx-2
      env: RBX_RUBY_COMPAT=2.1.0 RBX_VERSION=2.2.4
    - rvm: rbx
      env: RBX_RUBY_COMPAT=2.1.0 RBX_VERSION=2.2.4
