language: ruby
script: rake
notifications:
  recipients:
    - brixen@gmail.com
  email:
    on_success: change
    on_failure: always
rvm:
  - 2.0.0
matrix:
  exclude:
    - rvm: 2.0.0
  include:
    - rvm: rbx-2.6
      env: RBX_RUBY_COMPAT=2.1.0 RBX_VERSION=2.6
    - rvm: rbx-2
      env: RBX_RUBY_COMPAT=2.1.0 RBX_VERSION=2.6
    - rvm: rbx
      env: RBX_RUBY_COMPAT=2.1.0 RBX_VERSION=2.6
